### PR TITLE
Added the options to enable/disable loops and arrays

### PR DESCRIPTION
**Pull request by SakalisC**
Hello,

I needed the option to explicitly enable loops and/or array operations in the generated code, so I went ahead and created a patch for it.

### CODE REVIEW

**Comment by 0152la** [comment]
Hi, Chris.

I had a look at the code and I have the following observations:
- I assume the default behavior of the tool is to generate loops and arrays. Therefore, I don't see why their generation should be explicitly enabled.
- When you set no loop generation (_--no_loops_ flag), you also disable array generation. Why is this?

**Comment by SakalisC** [comment]
Hi,
- I thought it made sense to have a set of complementary flags, but I can't say that my feelings about it are too strong. If you think it's unnecessary, I can remove it.
- Arrays require loops for initialization, and potentially also for array operations (I am not 100% certain about the latter).

**Comment by SakalisC** [comment]
Sorry for the delay, I have now removed the extra options.

**Comment by SakalisC** [comment]
Any news on this?

**Comment by 0152la** [comment]
I was waiting for some comments from the other people; if there's nothing in the next few days, I'll check it and merge.

**Comment by SakalisC** [comment]
Thanks!

**Comment by 0152la** [comment]
Sorry for the delay; there was some internal talk about this. Thanks for the extra features.

**Pull request merged**
